# -*- coding: utf-8 -*-
"""Aula 30/03/26 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rs4FFQLd3_oyyWcDuT1U_bm6DhGtOK47
"""

import pandas as pd
import sklearn as sk
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split, PredefinedSplit
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.model_selection import GridSearchCV

df_treino= pd.read_csv('./split/treino.csv')
df_teste = pd.read_csv('./split/teste.csv')
df_val= pd.read_csv('./split/validacao.csv')


x_treino= df_treino.drop(columns=['overall'])
y_treino = df_treino['overall']

x_teste= df_teste.drop(columns=['overall'])
y_teste = df_teste['overall']

x_val = df_val.drop(columns=['overall'])
y_val = df_val['overall']



scaler = StandardScaler()
x_treino = scaler.fit_transform(x_treino)
x_teste = scaler.transform(x_teste)
x_val = scaler.transform(x_val)

x_combined = np.vstack((x_treino, x_val))
y_combined = np.hstack((y_treino, y_val))


test_fold = np.zeros(x_combined.shape[0])
test_fold[:len(x_treino)] = -1  # treino indices
test_fold[len(x_treino):] = 0   # Validation indices


ps = PredefinedSplit(test_fold)


# Define the parameter grid
param_grid = {
    'n_neighbors': [i for i in range (1, 61)],
    'weights': ['uniform', 'distance'],
    'metric': ['euclidean', 'manhattan'],
    'algorithm' : ['ball_tree', 'kd_tree'],
                   
}

# Create the GridSearchCV object
grid_search = GridSearchCV(KNeighborsRegressor(), param_grid, cv=ps, n_jobs = -1, scoring='neg_mean_absolute_error',
)

# Fit the grid search
grid_search.fit(x_combined, y_combined)

# Print the best parameters and score
print("Best parameters:", grid_search.best_params_)
print("Best cross-validation score:", grid_search.best_score_)

#exit()
melhor_modelo = grid_search.best_estimator_
print("\nMelhor configuração para o KNN")
print(melhor_modelo.get_params())
print("\nMelhor configuração:")
print("K: ",melhor_modelo.n_neighbors)
print("Weights: ",melhor_modelo.weights)

#**Aplicando o melhor modelo sobre o conjunto de teste**

print("\n\nDesempenho sobre o conjunto de teste")
opiniao = melhor_modelo.predict(x_teste)
mae_knn = mean_absolute_error(y_teste, opiniao)
print("\nK: ",melhor_modelo.n_neighbors,"\n MAE sobre o teste: ", mae_knn)
print("R2 Score: ", r2_score(y_teste,opiniao))

melhor_mae = mae_knn

#**ÁRVORE DE DECISÃO**

arvore = DecisionTreeRegressor()

parametros_arvore = {
    'criterion': ['squared_error', 'absolute_error'],
    'max_features': [None, 'sqrt', 'log2', 0.5],
    'max_depth': [None, 5, 10, 15, 20],
    'min_samples_split': [2, 10, 20, 30, 40, 50],
    'min_samples_leaf': [1, 5, 10, 15, 20, 25, 30],
}

busca = GridSearchCV(
    estimator=arvore,
    param_grid=parametros_arvore,
    scoring='neg_mean_absolute_error',
    cv=ps, 
    n_jobs=-1 
)

busca.fit(x_combined, y_combined)

melhor_arvore = busca.best_estimator_
print(f"\nMelhores Hiperparâmetros encontrados:\n{busca.best_params_}")

opiniao = melhor_arvore.predict(x_teste)

erro_arvore = mean_absolute_error(y_teste, opiniao)
print(f"Erro Médio da Melhor Árvore: {erro_arvore:.2f} pontos de Overall")
print("\nMelhor configuração para a AD")
print("Criterion: ",melhor_arvore.criterion," max_depth: ",melhor_arvore.max_depth," min_samples_leaf: ",melhor_arvore.min_samples_leaf," min_sample/s_split: ",melhor_arvore.min_samples_split," splitter: ",melhor_arvore.splitter)

#Aplicando a melhor configuração sobre o **Conjunto de Teste**

opiniao = melhor_arvore.predict(x_teste)
arvore_mae = mean_absolute_error(y_teste, opiniao)
print("mae sobre o teste: ", arvore_mae)

if(arvore_mae < melhor_mae):
    melhor_modelo = opiniao
    print("Novo melhor modelo é a arvore")