# -*- coding: utf-8 -*-
"""Aula 30/03/26 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rs4FFQLd3_oyyWcDuT1U_bm6DhGtOK47
"""

import pandas as pd
import sklearn as sk
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, r2_score

df_treino= pd.read_csv('./split/treino.csv')
df_teste = pd.read_csv('./split/teste.csv')
df_val= pd.read_csv('./split/validacao.csv')


x_treino= df_treino.drop(columns=['overall'])
y_treino = df_treino['overall']

x_teste= df_teste.drop(columns=['overall'])
y_teste = df_teste['overall']

x_val = df_val.drop(columns=['overall'])
y_val = df_val['overall']



scaler = StandardScaler()
x_treino = scaler.fit_transform(x_treino)
x_teste = scaler.transform(x_teste)
x_val = scaler.transform(x_val)

KNN = KNeighborsRegressor()
KNN.fit(x_treino,y_treino)
opiniao = KNN.predict(x_teste)

erro_medio = mean_absolute_error(y_teste, opiniao)
r2 = r2_score(y_teste, opiniao)

print("Erro Médio = ", erro_medio)
print("R2 Score = ", r2)



#atribuindo valores aos hiperparâmetros
#n_neighbors corresponde ao tamanho da vizinhança
#weights indica se os vizinhos terão pesos diferentes ou não. Pode assumir os valores uniform ou distante (ou callabe)


KNN = KNeighborsRegressor(n_neighbors=11)
KNN.fit(x_treino,y_treino)
opiniao = KNN.predict(x_teste)
erro_medio = mean_absolute_error(y_teste, opiniao)
r2 = r2_score(y_teste, opiniao)

print("Erro Médio = ", erro_medio)
print("R2 Score = ", r2)


"""**Atribuindo valores aos hiperparâmetros de forma explícita**

n_neighbors corresponde ao tamanho da vizinhança

weights indica se os vizinhos terão pesos diferentes ou não. Pode assumir os valores uniform ou distante (ou callabe)
"""

KNN = KNeighborsRegressor(n_neighbors=3,weights='distance')
KNN.fit(x_treino,y_treino)
opiniao = KNN.predict(x_teste)
erro_medio = mean_absolute_error(y_teste, opiniao)
r2 = r2_score(y_teste, opiniao)

print("Erro Médio = ", erro_medio)
print("R2 Score = ", r2)

"""**Usando a regra do cotovelo para encontrar o melhor K**

Neste processo, emprega-se o conjunto de validação
"""

erro_medio_v = []
for i in range (1,51):
  KNN = KNeighborsRegressor(n_neighbors=i,weights="distance")
  KNN.fit(x_treino,y_treino)
  opiniao = KNN.predict(x_val)
  erro_medio_v.append(mean_absolute_error(y_val, opiniao))
  print("K: ",i," mae: ",mean_absolute_error(y_val, opiniao))

print("\n\nVetor de Erros")
print(erro_medio_v)


melhor_k=np.argmin(erro_medio_v)
print("\nMelhor K:", melhor_k,"\n\n")

#aplica-se o K encontrado em um KNN sobre o conjunto de teste
KNN = KNeighborsRegressor(n_neighbors=melhor_k,weights="distance")
KNN.fit(x_treino,y_treino)
opiniao = KNN.predict(x_teste)
erro_medio = mean_absolute_error(y_teste, opiniao)
r2 = r2_score(y_teste, opiniao)

print("Erro Médio = ", erro_medio)
print("R2 Score = ", r2)

"""**Encontrando a melhor configuração de hiperparâmetros**

Neste exemplo, vamos empregar a estratégia de gridsearch
"""

menormae = 150
for j in ("distance","uniform"):
  for i in range (1,51):
    KNN = KNeighborsRegressor(n_neighbors=i,weights=j)
    KNN.fit(x_treino,y_treino)
    opiniao = KNN.predict(x_teste)
    mae = mean_absolute_error(y_teste, opiniao)

    print("K: ",i," Métrica: ",j," mae: ",mae)
    if (mae < menormae):
      menormae = mae
      melhor_modelo = KNN
      print(f"\033[91mmelhorou\033[0m")

print("\nMelhor configuração para o KNN")
print(melhor_modelo.get_params())
print("\nMelhor configuração:")
print("K: ",melhor_modelo.n_neighbors)
print("Weights: ",melhor_modelo.weights)

"""**Aplicando o melhor modelo sobre o conjunto de teste**"""

print("\n\nDesempenho sobre o conjunto de teste")
opiniao = melhor_modelo.predict(x_teste)
print("\nK: ",melhor_modelo.n_neighbors," mae sobre o teste: ",mean_absolute_error(y_teste, opiniao))

"""**ÁRVORE DE DECISÃO**

vamos repetir a mesma ideia, aplicando agora um classificador hierárquico
"""



AD = DecisionTreeRegressor()
AD.fit(x_treino,y_treino)
opiniao = AD.predict(x_teste)
print("MAE com parâmetros default: ",mean_absolute_error(y_teste, opiniao))

"""Aplicando agora valores escolhidos a priori aos hiperparâmetros"""

AD = DecisionTreeRegressor(criterion='absolute_error',max_depth=7,min_samples_leaf=3,min_samples_split=5,splitter='best')
AD.fit(x_treino,y_treino)
opiniao = AD.predict(x_teste)
erro_medio = mean_absolute_error(y_teste, opiniao)
r2 = r2_score(y_teste, opiniao)

print("Erro Médio = ", erro_medio)
print("R2 Score = ", r2)

"""Explorando diversas combinações de hiperparâmetros usando o GridSearch"""

menormae = 150
for j in ("absolute_error","poisson"):  #criterion
  for i in range (5,15):      #max_depth
    for k in range (20,55):    #min_samples_leaf
      for l in range (50,100):  #min_samples_split
        for m in ('best','random'): #splitter
          AD = DecisionTreeRegressor(criterion=j,max_depth=i,min_samples_leaf=k,min_samples_split=l,splitter=m)
          AD.fit(x_treino,y_treino)
          opiniao = AD.predict(x_val)
          mae = mean_absolute_error(y_teste, opiniao)
          print("Criterion: ",j," max_depth: ",i," min_samples_leaf: ",k," min_samples_split: ",l," splitter: ",m," mae: ",mae)
          if (mae < menormae):
            menormae = mae
            melhor_modelo = AD
            print(f"\033[91mmelhorou\033[0m")

print("\nMelhor configuração para a AD")
print("Criterion: ",melhor_modelo.criterion," max_depth: ",melhor_modelo.max_depth," min_samples_leaf: ",melhor_modelo.min_samples_leaf," min_samples_split: ",melhor_modelo.min_samples_split," splitter: ",melhor_modelo.splitter," Acc: ",menormae)

"""Aplicando a melhor configuração sobre o **Conjunto de Teste**"""

opiniao = melhor_modelo.predict(x_teste)
print("mae sobre o teste: ", mean_absolute_error(y_teste, opiniao))